### PR TITLE
Use @nteract/outputs in @nteract/notebook-app-component

### LINKED ISSUE #3342: <Output> Picker
Next steps for the `@nteract/outputs`:

* [x] Write our "official" output components that would handle all the output types just like what we previously handled in `packages/display-area/src/output.js`
  * [x] `<ExecuteResult>`
  * [x] `<DisplayData>`
  * [x] `<Traceback />` (or call it `<JupyterError />`
  * [x] `<Stream />`
* [x] Create `<Media />` components for all the transforms (or adapt them to the new style which only needs adding a `mediaType` key) 
* [ ] Extract styles out of `packages/presentational-components/src/components/outputs.js` that belong in the respective media or outputs, possibly packaged as:

```js
export userOutputStyle = css`
  .userOutput :global(table) {
    /* yay css */
  }
`;
```

then use them in `<Media.HTML />` and `@nteract/markdown`'s markdown.

* [x] Integrate the Output picker, RichMedia, and all these components into the notebook app component
* [ ] Deprecate `@nteract/display-area`

### PR DESCRIPTION
**Pull request by captainsafia**
Closes https://github.com/nteract/nteract/issues/3342.

### CODE REVIEW

File: packages/jupyter-widgets/src/index.tsx [hunk 1]
```diff
@@ -19,7 +19,7 @@ type Props = {
  * Even though it may appear to be pure, since it doesn't have react state, this
  * component's iframe maintains it's own state in communication with the kernel.
  */
-export class WidgetDisplay extends React.Component<Props> {
+export class WidgetDisplay extends React.Component<Partial<Props>> {
```
Comment (captainsafia) [inline packages/jupyter-widgets/src/index.tsx:22]: Here and elsewhere, I had to require that transform components take a Partial as a prop since the picker passes the props to the components using `React.cloneElement` and the props aren't set on these components when they are children of `Output`.

File: packages/outputs/src/components/kernel-output-error.tsx [hunk 2]
```diff
@@ -42,17 +42,17 @@ const PlainKernelOutputError = (props: Props) => {
...
-  traceback: []
-};
-
 export const KernelOutputError = styled(PlainKernelOutputError)`
   & code {
     white-space: pre-wrap;
   }
 `;
 
+KernelOutputError.defaultProps = {
```
Comment (captainsafia) [inline packages/outputs/src/components/kernel-output-error.tsx:49]: I had to set the props on the styled component because styled-components clobbers the defaultProps initialization for some reason.

File: packages/notebook-app-component/src/notebook-app.tsx [hunk 3]
```diff
@@ -252,34 +268,69 @@ class AnyCell extends React.PureComponent<AnyCellProps> {
...
+                  <DisplayData>
+                    <Media.HTML />
+                    <Media.Image />
+                    <Media.JavaScript />
+                    <Media.Json />
+                    <Media.LaTeX />
+                    <Media.Markdown />
+                    <Media.Plain />
+                    <Media.SVG />
+                    <DataResourceTransform />
```
Comment (rgbkrk) [inline packages/notebook-app-component/src/notebook-app.tsx]:
```suggestion
                    <DataResourceTransform onMetadataChange={this.props.updateOutputMetadata} />
```

File: packages/jupyter-widgets/src/index.tsx (hunk 1 above)
Comment (rgbkrk) [reply packages/jupyter-widgets/src/index.tsx:22]: Oh... Interesting. I wonder if there's a good paradigm for having a version that can take a partial and another that must have the props set. We're probably safer if this is `Partial` and checked below though. One thing though... I feel like we have to require `mediaType` even though we set it as a `defaultProp` so that the `Output` component can use it.

**Comment by rgbkrk** [comment]
First off, fantastic! I'm so happy to switch to this more compound API.

I'm going to re-iterate some stuff that was in slack messages, for the benefit of everyone.

We don't want to include all the "advanced" transforms in our default app component. The component should be flexible enough to set exactly which media components to use for each media type (and in which order). The main reasons are:

* Ability to not include media types or components deemed unsafe
* Enable media types & components custom to a deployment (customized version of Plotly, some special media type)
* Ability to code split and load transforms dynamically (improve initial render / user experience)
  * Jupyter extension does this currently here: https://github.com/nteract/nteract/blob/master/applications/jupyter-extension/nteract_on_jupyter/app/contents/notebook.tsx#L76-L82

Safia said it best the problem we need to solve:

> Now that media transforms are passed as child components instead of props we need a way to configure which transforms will be rendered on the page.

Our current way of passing the transforms and displayOrder as an `ownProp` is exacerbating our perf problem (#3434), so we need to move them to somewhere else. My proposal: create redux actions for registering media types and set them on the state tree likely under `state.core.entities.media`.

The _wonderful_ thing about this is that it would make it easier for all the different segments that use these same media transform components to pluck them off in their `mapStateToProps` connected components easily. This includes the editor, display data, execute result, and pagers.

What I'm stepping past though is how the custom media types would get access to things to `models`, `onMetadataChange` (maybe it's fine if they all get it?), etc.

**Comment by rgbkrk** [comment]
We could do a separate PR that does the switch over to storing the transforms in the redux store first.

* Expect transforms and displayOrder as they currently do to be on `state.core.entities.media.(transforms|displayOrder)`
* Desktop can literally set all the ones it's using as part of the `createStore` instead of dynamically load them
* Jupyter Extension can `dispatch` to add/set transforms

Alternatively, that could be part of this PR and just go straight after our final implementation. I'll leave that up to you @captainsafia.

File: packages/outputs/src/components/execute-result.tsx [hunk 4]
```diff
@@ -45,7 +45,7 @@ export const ExecuteResult = (props: Props) => {
 };
 
 ExecuteResult.defaultProps = {
-  outputType: "pyout",
+  output_type: "execute_result",
```
Comment (rgbkrk) [inline packages/outputs/src/components/execute-result.tsx:48]: Good catch on this incorrect `output_type`. That's the old messaging spec there. 😬

File: packages/outputs/src/components/kernel-output-error.tsx [hunk 5]
```diff
@@ -42,17 +42,17 @@ const PlainKernelOutputError = (props: Props) => {
...
 };
 
-PlainKernelOutputError.defaultProps = {
-  outputType: "error",
-  ename: "",
-  evalue: "",
-  traceback: []
-};
-
 export const KernelOutputError = styled(PlainKernelOutputError)`
```
Comment (rgbkrk) [inline packages/outputs/src/components/kernel-output-error.tsx:45]: I just noticed that we're missing the passing of a `className` into the `<Ansi` child of `PlainKernelOutputError`. `styled-components` won't actually style this component as a result.

File: packages/outputs/src/components/media/image.tsx [hunk 6]
```diff
@@ -4,15 +4,15 @@ import styled from "styled-components";
 interface Props {
   data: string;
   mediaType: "image/png" | "image/jpeg" | "image/gif";
-  metadata: any;
+  metadata?: { height: number; width: number };
```
Comment (rgbkrk) [inline packages/outputs/src/components/media/image.tsx]: Each of these props should also be optional `height?: number` in case `metadata` is defined.

File: packages/outputs/src/components/rich-media.tsx [hunk 7]
```diff
@@ -98,6 +103,7 @@ export class RichMedia extends React.Component<RichMediaProps, State> {
     let chosenOne: React.ReactChild | null = null;
 
     const data = this.props.data;
+    const mimetype = richestMimetype(data, displayOrder, transforms);
```
Comment (rgbkrk) [inline packages/outputs/src/components/rich-media.tsx]: Could probably name this var `mediaType` to match down below.

Comment (rgbkrk) [reply packages/outputs/src/components/rich-media.tsx]: Oh wait. We don't need this function any more.

The order is picked below by the order of when the children appear.

Comment (rgbkrk) [reply packages/outputs/src/components/rich-media.tsx]: This is documented well in the markdown in https://components.nteract.io/#richmedia yet not in the component.

> The `<RichMedia />` component accepts the whole media bundle from a kernel via the `data` prop and all the elements for rendering media types as children. The order of the children states their richness from highest to lowest.

File: packages/outputs/src/components/rich-media.tsx [hunk 8]
```diff
@@ -109,7 +115,7 @@ export class RichMedia extends React.Component<RichMediaProps, State> {
       if (
         childElement.props &&
         childElement.props.mediaType &&
-        childElement.props.mediaType in data
```
Comment (rgbkrk) [inline packages/outputs/src/components/rich-media.tsx]: This original check basically made sure that the `mediaType` of a child matched that of one in `data`, checking in order.

```jsx
<RichMedia>
  <Plain />
  <HTML />
</RichMedia>
```

means that Plain is preferred over HTML whereas 

```jsx
<RichMedia>
  <HTML />
  <Plain />
</RichMedia>
```

means that HTML is preferred.

File: packages/records/__tests__/appendOutput.spec.ts [hunk 9]
```diff
@@ -3,46 +3,46 @@ import appendOutput, { mutate } from "../src/outputs/append-output";
...
-        outputType: "error",
+        output_type: "error",
         ename: "well",
         evalue: "actually",
         traceback: []
       }
     ];
     const newOutputs = appendOutput(outputs, {
-      outputType: "displayData",
+      output_type: "displayData",
```
Comment (rgbkrk) [inline packages/records/__tests__/appendOutput.spec.ts]: Glad I saw this. The `output_type` name needs to match the jupyter spec so something (before this PR) was erroneously using the `camelCase` `displayData` instead of `display_data`.

File: packages/records/__tests__/index.spec.ts [hunk 10]
```diff
@@ -61,7 +61,7 @@ describe("display_data output", () => {
       })
     ).toEqual(
       displayData({
-        outputType: "display_data",
+        output_type: "display_data",
```
Comment (rgbkrk) [inline packages/records/__tests__/index.spec.ts:64]: Yet this one has the write casing for `display_data`. Must just be the test above.

File: packages/transform-dataresource/src/index.tsx [hunk 11]
```diff
@@ -486,7 +490,7 @@ class DataResourceTransform extends React.Component<Props, State> {
 
     return (
       <div>
-        <MetadataWarning metadata={this.props.metadata} />
+        <MetadataWarning metadata={this.props.metadata!} />
```
Comment (rgbkrk) [inline packages/transform-dataresource/src/index.tsx:493]: Good way of handling this for now.

File: styleguide.config.js [hunk 12]
```diff
@@ -74,16 +74,17 @@ module.exports = {
...
       fs: "empty",
       child_process: "empty",
-      net: "empty"
-    },
-    resolve: {
-      extensions: [".ts", ".tsx"]
-    },
-    module: {
+      net: "empty",
+      canvas: "empty"
```
Comment (rgbkrk) [inline styleguide.config.js:82]: A+

File: packages/records/__tests__/appendOutput.spec.ts (hunk 9 above)
Comment (captainsafia) [reply packages/records/__tests__/appendOutput.spec.ts]: Ooooh! Good catch. Thanks!

File: packages/outputs/src/components/rich-media.tsx (hunk 7 above)
Comment (captainsafia) [reply packages/outputs/src/components/rich-media.tsx]: Oh! My bad. I totally missed this documentation (which is funny because didn't I write it?). I thought we needed to keep this `richestMime` logic back. This actually simplifies a whole lot.

File: packages/outputs/src/components/media/image.tsx (hunk 6 above)
Comment (captainsafia) [reply packages/outputs/src/components/media/image.tsx]: Great call!

File: packages/outputs/src/components/rich-media.tsx (hunk 7 above)
Comment (rgbkrk) [reply packages/outputs/src/components/rich-media.tsx]: @alexandercbooth and I wrote this one like 4-5 months ago. Since we had not done the integration work (like you've done here), we never got to kill off the old `richestMime`.

Comment (captainsafia) [reply packages/outputs/src/components/rich-media.tsx]: OK! That makes me feel a little bit better about missing this. Code is actually much cleaner without it. Feels good to not rely on all the displayOrder stuff.

**Comment by captainsafia** [comment]
Thanks for posting that summary, @rgbkrk!

Based on the problem definition that I mentioned, I thought up a possible solution we could use to address this. This solution uses the [react-loadable](https://www.npmjs.com/package/react-loadable) package which I quite liked for (1) its API, (2) documentation, and (3) decent adoption rate. With React loadable, we can define as Loadable component for each transform as such. Here's some example code that shows how we can use this component and also how we might be able to use the `render` API within react-loadable to pass props like onMetadataChange to components.

```
import Loadable from "react-loadable";

export default class Notebook extends React.Component {
  DataExplorer = Loadable({
    loader: () => import("@nteract/transform-dataresource"),
    loading: NullDataExplorerTransform,
    render(loaded, props) {
      this.props.dispatchAddTransforms(
        <loaded.export
          onMetadataChange={this.props.dispatchOnMetadataChange})
          )}
        />
      );
    }
  });

  render() {
    return <App contentRef={this.props.contentRef} transforms={this.props.transformsFromState}/>;
  }
}

const makeMapStateToProps = () => {
    return (state) => {
        return { transformsFromState: state.transforms }
    }
}

const makeMapDispatchToProps = () => {
  return dispatch => {
    return {
      dispatchAddTransforms: dispatch(actions.addTransforms),
      dispatchOnMetadataChange: dispatch(actions.onMetadataChange)
    };
  };
};

const ConnectedNotebook = connect(
  makeMapStateToProps,
  makeMapDispatchToProps
)(Notebook);

```

If this approach sounds good, to keep the velocity moving, I'm in favor of merging this and implementing this logic in a separate PR.

**Comment by rgbkrk** [comment]
I'm in slight agreement. Let me look over the current state.

File: applications/desktop/src/notebook/index.tsx [hunk 13]
```diff
@@ -122,8 +122,6 @@ export default class App extends React.PureComponent {
           <NotebookApp
             // The desktop app always keeps the same contentRef in a browser window
             contentRef={contentRef}
-            transforms={transforms}
-            displayOrder={displayOrder}
```
Comment (rgbkrk) [inline applications/desktop/src/notebook/index.tsx:126]: 👍

File: packages/notebook-app-component/package.json [hunk 14]
```diff
@@ -17,10 +17,18 @@
...
     "@nteract/octicons": "^1.0.4-alpha.0",
+    "@nteract/outputs": "^1.0.4-alpha.0",
     "@nteract/presentational-components": "^2.0.4-alpha.0",
     "@nteract/selectors": "^1.0.4-alpha.0",
+    "@nteract/transform-dataresource": "^5.0.4-alpha.0",
+    "@nteract/transform-geojson": "^4.0.4-alpha.0",
+    "@nteract/transform-model-debug": "^4.0.4-alpha.0",
+    "@nteract/transform-plotly": "^4.0.4-alpha.0",
+    "@nteract/transform-vdom": "^3.0.4-alpha.0",
+    "@nteract/transform-vega": "^4.0.4-alpha.0",
```
Comment (rgbkrk) [inline packages/notebook-app-component/package.json:31]: I still don't want these as direct dependencies within the notebook app component

File: packages/notebook-preview/__tests__/__snapshots__/index.test.tsx.snap [hunk 15]
```diff
@@ -223,19 +223,19 @@ print('hey')
...
-                "image/gif": [Function],
-                "image/jpeg": [Function],
-                "image/png": [Function],
-                "image/svg+xml": [Function],
-                "text/html": [Function],
-                "text/latex": [Function],
-                "text/markdown": [Function],
-                "text/plain": [Function],
-              }
+              Array [
```
Comment (rgbkrk) [inline packages/notebook-preview/__tests__/__snapshots__/index.test.tsx.snap]: There must be either a prop ready for deletion or a defaultProp that needs to delete these transforms.

File: packages/outputs/__tests__/__snapshots__/media.spec.tsx.snap [hunk 16]
```diff
@@ -1055,13 +1055,175 @@ exports[`HTML renders direct HTML 1`] = `
...
     }
-  />
+  >
+    <StyledComponent
+      dangerouslySetInnerHTML={
+        Object {
+          "__html": "<b>cats are best</b>",
+        }
+      }
+      forwardedComponent={
```
Comment (rgbkrk) [inline packages/outputs/__tests__/__snapshots__/media.spec.tsx.snap:1071]: I wonder why this is all being written out here...

File: packages/outputs/src/components/kernel-output-error.tsx [hunk 17]
```diff
@@ -39,20 +39,24 @@ const PlainKernelOutputError = (props: Props) => {
...
-  return <Ansi linkify={false}>{kernelOutputError.join("\n")}</Ansi>;
-};
-
-PlainKernelOutputError.defaultProps = {
-  outputType: "error",
-  ename: "",
-  evalue: "",
-  traceback: []
+  return (
+    <Ansi className="stacktrace" linkify={false}>
```
Comment (rgbkrk) [inline packages/outputs/src/components/kernel-output-error.tsx]: The className should be `this.props.className`. That's what `styled-components` is going to pass through as the `className`(`s`)

File: packages/outputs/src/components/kernel-output-error.tsx [hunk 18]
```diff
@@ -39,20 +39,24 @@ const PlainKernelOutputError = (props: Props) => {
...
+      {kernelOutputError.join("\n")}
+    </Ansi>
+  );
 };
 
 export const KernelOutputError = styled(PlainKernelOutputError)`
-  & code {
+  & .stracktrace {
```
Comment (rgbkrk) [inline packages/outputs/src/components/kernel-output-error.tsx]: Typo here, though I think you can now just convert this whole thing to:

```css
white-space: pre-wrap;
```

with no extra qualifiers.

File: packages/transforms/src/index.tsx [hunk 19]
```diff
@@ -80,7 +80,7 @@ export function richestMimetype(
       .sort((a, b) => order.indexOf(a) - order.indexOf(b))[0]
   );
 }
-export const transforms = standardTransforms;
+export const transforms = tfs;
```
Comment (rgbkrk) [inline packages/transforms/src/index.tsx]: Doesn't this need to stay as `standardTransforms`?

Comment (captainsafia) [reply packages/transforms/src/index.tsx]: Yep. You're right. Since they are no longer passed to the NotebookApp component, this can be `standardTransforms`. I had changed it to deal with a type error that no longer exists.

File: packages/notebook-app-component/src/notebook-app.tsx [hunk 20]
```diff
@@ -16,19 +15,33 @@ import {
...
 
+import PlotlyTransform, {
+  PlotlyNullTransform
+} from "@nteract/transform-plotly";
+import GeoJSONTransform from "@nteract/transform-geojson";
+import ModelDebug from "@nteract/transform-model-debug";
+import DataResourceTransform from "@nteract/transform-dataresource";
+import { VegaLite1, VegaLite2, Vega2, Vega3 } from "@nteract/transform-vega";
+import VDOMDisplay from "@nteract/transform-vdom";
+import { WidgetDisplay } from "@nteract/jupyter-widgets";
```
Comment (rgbkrk) [inline packages/notebook-app-component/src/notebook-app.tsx]: Since we're talking about merging this in sooner rather than later, maybe we should take out the custom transforms for now and only stick in the default media ones.

File: packages/notebook-app-component/src/notebook-app.tsx [hunk 21]
```diff
@@ -252,34 +263,69 @@ class AnyCell extends React.PureComponent<AnyCellProps> {
...
-                  displayOrder={this.props.displayOrder}
-                  transforms={this.props.transforms}
-                  theme={this.props.theme}
-                  models={this.props.models}
-                  channels={this.props.channels}
-                  onMetadataChange={this.props.updateOutputMetadata}
-                  index={index}
-                  metadata={metadata}
-                />
+                <Output output={output.toJS()} key={index}>
```
Comment (rgbkrk) [inline packages/notebook-app-component/src/notebook-app.tsx]: I also just noticed this... Which is definitely going to cause some perf thrashing. It's going to create the object each time. I _think_ because our records have the same structure now due to how you aligned everything on `camel_case` we can just pass the record `output`.

Comment (captainsafia) [reply packages/notebook-app-component/src/notebook-app.tsx]: Yep. Passing just record works now. I can't recall what error I was addressing when I added this. I think it might have had something to do with a type error.

File: applications/jupyter-extension/nteract_on_jupyter/app/index.tsx [hunk 22]
```diff
@@ -11,10 +11,22 @@ import {
   makeEntitiesRecord,
   makeHostsRecord,
   makeJupyterHostRecord,
-  makeStateRecord
+  makeStateRecord,
+  makeTransfromsRecord
```
Comment (rgbkrk) [inline applications/jupyter-extension/nteract_on_jupyter/app/index.tsx]:
```suggestion
  makeTransformsRecord
```

File: applications/jupyter-extension/nteract_on_jupyter/app/index.tsx [hunk 23]
```diff
@@ -104,6 +116,20 @@ function main(rootEl: Element, dataEl: Node | null) {
               filepath: config.contentsPath
             })
           )
+        }),
+        transforms: makeTransfromsRecord({
```
Comment (rgbkrk) [inline applications/jupyter-extension/nteract_on_jupyter/app/index.tsx]:
```suggestion
        transforms: makeTransformsRecord({
```

File: packages/notebook-app-component/src/notebook-app.tsx [hunk 24]
```diff
@@ -252,34 +253,69 @@ class AnyCell extends React.PureComponent<AnyCellProps> {
...
-                <RichestMime
-                  metadata={{ expanded: true }}
-                  className="pager"
-                  displayOrder={this.props.displayOrder}
-                  transforms={this.props.transforms}
-                  bundle={pager}
-                  theme={this.props.theme}
-                  key={key}
-                />
+                <DisplayData {...pager}>
```
Comment (rgbkrk) [inline packages/notebook-app-component/src/notebook-app.tsx]: What's up with the splat prop on the pager? Should this just be explicit about `data={pager.data}`, etc.?

File: packages/outputs/src/components/transform-media.tsx [hunk 25]
```diff
@@ -0,0 +1,79 @@
+import React from "react";
```
Comment (rgbkrk) [inline packages/outputs/src/components/transform-media.tsx]: We should put these connected components within `notebook-app-component` since nothing else in this outputs package is a connected component. The `@nteract/outputs` components shouldn't have to rely on `core`, `types`, `redux`, etc. as we want Hydrogen to be willing to adopt it. The main barrier would be that this would install a _lot_ of things on atom plugin install that isn't even used.

File: packages/outputs/src/components/transform-media.tsx [hunk 26]
```diff
@@ -0,0 +1,79 @@
...
+import { connect } from "react-redux";
+import { Dispatch } from "redux";
+
+import { JSONObject } from "@nteract/commutable";
+import { actions, selectors } from "@nteract/core";
+import { AppState, ContentRef } from "@nteract/types";
+
+interface OwnProps {
+  id: string;
```
Comment (rgbkrk) [inline packages/outputs/src/components/transform-media.tsx]: Is the `id` being put in here for the future of having output IDs? If so, we should remove it for now so we're not leaving clutter that we have to clean up later (in case we don't get to revisit it).

Comment (captainsafia) [reply packages/outputs/src/components/transform-media.tsx]: This is the cellId. It's used to pull out the cell so that the outputs can be pulled from that. I realize that we modeled this to take an output, not a cell, so I will update.

File: packages/outputs/src/components/transform-media.tsx (hunk 25 above)
Comment (captainsafia) [reply packages/outputs/src/components/transform-media.tsx]: Makes sense. I'll move the file.

File: packages/notebook-app-component/src/notebook-app.tsx (hunk 24 above)
Comment (captainsafia) [reply packages/notebook-app-component/src/notebook-app.tsx]: Yeah. We can be explicit here.

File: applications/jupyter-extension/nteract_on_jupyter/app/index.tsx (hunk 23 above)
Comment (captainsafia) [reply applications/jupyter-extension/nteract_on_jupyter/app/index.tsx]: Oh gosh! I'm such a goof. I spent way too long trying to figure this out and didn't see that.

File: packages/outputs/src/components/transform-media.tsx (hunk 26 above)
Comment (rgbkrk) [reply packages/outputs/src/components/transform-media.tsx]: Ahhhh! I suppose you need it for the action though so it's probably fine. Should just call it `cellId`

File: applications/desktop/src/notebook/index.tsx [hunk 27]
```diff
@@ -59,6 +59,73 @@ const store = configureStore({
...
+          "text/html",
+          "text/markdown",
+          "text/latex",
+          "image/svg+xml",
+          "image/gif",
+          "image/png",
+          "image/jpeg",
+          "text/plain"
+        ]),
+        byId: Immutable.Map({
```
Comment (rgbkrk) [inline applications/desktop/src/notebook/index.tsx:87]: Are `handlers` and `byId` overlapping in data? Do we only need `byId`?

File: applications/jupyter-extension/nteract_on_jupyter/app/contents/notebook.tsx [hunk 28]
```diff
@@ -141,12 +77,34 @@ export default class Notebook extends React.PureComponent<
...
+            mediaType: transform.MIMETYPE,
+            component: transform
+          })
+        );
+      }
+    };
+  };
+  return mapDispatchToProps;
+};
+
```
Comment (rgbkrk) [inline applications/jupyter-extension/nteract_on_jupyter/app/contents/notebook.tsx:106]: I'm really liking how you've done the `addTransform` here. This is solid.

File: packages/actions/src/actionTypes/index.ts [hunk 29]
```diff
@@ -167,13 +167,19 @@ export interface MergeConfigAction {
 }
 
 export const LOAD_CONFIG = "LOAD_CONFIG";
-export interface LoadConfigAction { type: "LOAD_CONFIG" }
+export interface LoadConfigAction {
+  type: "LOAD_CONFIG";
+}
```
Comment (rgbkrk) [inline packages/actions/src/actionTypes/index.ts:172]: I look forward to when all the tslint and prettier stuff is automated so we don't sneak in accidental changes to review. 😅

File: packages/actions/src/actionTypes/index.ts [hunk 30]
```diff
@@ -217,5 +223,23 @@ export interface PublishGist {
...
+
+export const REMOVE_TRANSFORM = "REMOVE_TRANSFORM";
+export interface RemoveTransform {
+  type: "REMOVE_TRANSFORM";
+  payload: {
+    mediaType: string;
+    component: any;
+  };
+}
```
Comment (rgbkrk) [inline packages/actions/src/actionTypes/index.ts:242]: Not sure when we'd use this but it makes sense.

File: packages/actions/src/actions/index.ts [hunk 31]
```diff
@@ -240,6 +240,26 @@ export function publishGist(payload: {
   };
 }
 
+export function removeTransform(payload: {
```
Comment (rgbkrk) [inline packages/actions/src/actions/index.ts]: You don't have to do it in this PR if you don't want, thought I'd point out though that you can use `payload: actionTypes.RemoveTransform["payload"]` to tie this to the action's payload type directly.

File: packages/notebook-app-component/package.json (hunk 14 above)
Comment (rgbkrk) [reply packages/notebook-app-component/package.json:31]: With the refactor you've done here I _think_ you can delete these from the `package.json` and the `tsconfig.json`

File: packages/notebook-app-component/src/notebook-app.tsx [hunk 32]
```diff
@@ -251,34 +253,41 @@ class AnyCell extends React.PureComponent<AnyCellProps> {
...
-                  theme={this.props.theme}
-                  models={this.props.models}
-                  channels={this.props.channels}
-                  onMetadataChange={this.props.updateOutputMetadata}
-                  index={index}
-                  metadata={metadata}
-                />
+                <Output output={output} key={index}>
+                  <TransformMedia
+                    output_type={"display_data"}
```
Comment (rgbkrk) [inline packages/notebook-app-component/src/notebook-app.tsx:274]: This is at least cleaner than before and now we have a nice connected component to work with. Well done.

File: packages/notebook-app-component/src/transform-media.tsx [hunk 33]
```diff
@@ -0,0 +1,108 @@
...
+    outputData.keys((mediaType: string) => {
+      if (handlers[mediaType] && order.includes(mediaType)) {
+        return mediaType;
+      }
+    })
+  );
+  return validMediaTypes
+    .sort((a: string, b: string) => order.indexOf(a) - order.indexOf(b))
+    .get(0);
+};
```
Comment (rgbkrk) [inline packages/notebook-app-component/src/transform-media.tsx:56]: I enjoy that this is clean enough we can optimize it later nicely.

File: packages/notebook-app-component/src/transform-media.tsx [hunk 34]
```diff
@@ -0,0 +1,108 @@
...
+  };
+  return mapDispatchToProps;
+};
+
+const TransformMedia = connect(
+  makeMapStateToProps,
+  makeMapDispatchToProps
+)(PureTransformMedia);
+
+export default TransformMedia;
```
Comment (rgbkrk) [inline packages/notebook-app-component/src/transform-media.tsx:108]: I'm really happy about this overall setup! It simplifies our rendering of rich outputs while optimizing how we work with them. One thing I feel like with this partial rewrite though is that we're missing some of the comments in either the old display-area bits or the `rich-media` component docs that provide context about selecting the richest. A few of these functions look eminently testable that we _might_ have had prior tests for(?).

File: packages/notebook-app-component/src/notebook-app.tsx [hunk 35]
```diff
@@ -251,34 +253,41 @@ class AnyCell extends React.PureComponent<AnyCellProps> {
...
+                <DisplayData data={pager.data} metadata={pager.metadata}>
+                  <Media.Json />
+                  <Media.JavaScript />
+                  <Media.HTML />
+                  <Media.Markdown />
+                  <Media.LaTeX />
+                  <Media.SVG />
+                  <Media.Image />
+                  <Media.Plain />
+                </DisplayData>
```
Comment (rgbkrk) [inline packages/notebook-app-component/src/notebook-app.tsx]: Since pagers haven't been showing anything much richer than HTML or Plain most of the time, I think this is a good solution. Also it's ok to use `<RichMedia>` from `@nteract/outputs` here.

File: packages/notebook-app-component/tsconfig.json [hunk 36]
```diff
@@ -17,6 +17,14 @@
...
-    { "path": "../types" }
+    { "path": "../types" },
+    { "path": "../outputs" },
+    { "path": "../transform-plotly" },
+    { "path": "../transform-geojson" },
+    { "path": "../transform-model-debug" },
+    { "path": "../transform-dataresource" },
+    { "path": "../transform-vega" },
+    { "path": "../transform-vdom" },
+    { "path": "../jupyter-widgets" }
```
Comment (rgbkrk) [inline packages/notebook-app-component/tsconfig.json]: Yup, looks like you can take `transform-*` and `jupyter-widgets` out of here since they're not getting used in `notebook-app-component` anymore.

Comment (captainsafia) [reply packages/notebook-app-component/tsconfig.json]: Oh. Good call.

File: packages/notebook-app-component/src/notebook-app.tsx (hunk 35 above)
Comment (captainsafia) [reply packages/notebook-app-component/src/notebook-app.tsx]: Makes sense.

File: packages/notebook-app-component/src/transform-media.tsx (hunk 34 above)
Comment (captainsafia) [reply packages/notebook-app-component/src/transform-media.tsx:108]: Hm. Yeah. I'll have to look into this as well as updating the component docs.

File: packages/actions/src/actions/index.ts (hunk 31 above)
Comment (captainsafia) [reply packages/actions/src/actions/index.ts]: Ah yes. Fixed.

File: applications/desktop/src/notebook/index.tsx (hunk 27 above)
Comment (captainsafia) [reply applications/desktop/src/notebook/index.tsx:87]: Yeah. We only need byId so I'll remove handlers.

**Review by rgbkrk — APPROVED** [review]
Alright, looking great. The docs + tests can come in a follow up PR.

Thanks for carrying this through to completion!
