### PR TITLE
fix: correct the mimetype compare function

### LINKED ISSUE #1798: richestMimetype is returning the wrong value
```js
> richestMimetype({'image/png': '999', 'text/plain': '123', 'application/vnd.vegalite.v1+json': {}})
text/plain
```

### PR DESCRIPTION
**Pull request by rgbkrk**
Fixes #1798.

/cc @lgeiger

### CODE REVIEW

**Comment by rgbkrk** [comment]
I'm going to ship after this because I noticed that it was only showing `text/plain` on notebooks on commuter.

File: packages/transforms/src/index.js [hunk 1]
```diff
@@ -75,7 +75,7 @@ export function richestMimetype(
       // we can only use those we have a transform for
       .filter(mimetype => tf[mimetype] && order.includes(mimetype))
       // the richest is based on the order in displayOrder
-      .sort(mimetype => order.indexOf(mimetype))[0]
```
Comment (theengineear) [inline packages/transforms/src/index.js:78]: Is this a breaking change? If you're depending on whatever the sort order currently is, won't this new sort break your code?

Comment (theengineear) [reply packages/transforms/src/index.js:78]: Nvm, @rgbkrk and I chatted about it.

**Review by theengineear — APPROVED** [review]

File: packages/transforms/src/index.js (hunk 1 above)
Comment (rgbkrk) [reply packages/transforms/src/index.js:78]: It was using just fine logic when this was using Immutable.js. `sort` now needs to return -1, 0, or 1 because it's a regular js sort. This was making all outputs end up as `text/plain`.

**Comment by lgeiger** [comment]
Thanks for fixing this!

File: packages/transforms/src/index.js [hunk 2]
```diff
@@ -75,7 +75,7 @@ export function richestMimetype(
...
+      .sort((a, b) => order.indexOf(a) - order.indexOf(b))[0]
```
Comment (rgbkrk) [inline packages/transforms/src/index.js:78]: It was really hard not to precompute these, which makes me want to create a real class for the displayOrder and transforms (which would likely be mutative for adding in new mimetypes or replacing old ones).
