### PR TITLE
fix(code-cell): add ability to unhide code cells.

### LINKED ISSUE #668: Need a way to unhide input when both input hidden and no output
If you toggle inputs, on a cell that either has output hidden or no outputs, 

screen shot 2016-09-02 at 8 41 08 am

At first there's the cell menu, mostly as a leftover though

screen shot 2016-09-02 at 8 41 24 am

As soon as you focus on another cell though, you can't get that cell back.

screen shot 2016-09-02 at 8 41 39 am

Suggestions for "fixes":
- Top level menu option to show all
- Some sort of thin representation of the cell when you hover (?)

This probably seems like an edge case of usage - it's not. One of the main reasons to hide input is for others to consume as a whole document with no code (like a report). There will be cells that don't have outputs in those cases (getting data ready, etc.).

### PR DESCRIPTION
**Pull request by aleury**
Closes #668

### CODE REVIEW

File: test/utils.js [hunk 1]
```diff
@@ -23,9 +23,11 @@ import {
 const sinon = require('sinon');
 
 export function dummyStore(config) {
-  const notebook = appendCell(emptyNotebook, emptyCodeCell).setIn([
+  let notebook = appendCell(emptyNotebook, emptyCodeCell).setIn([
     'metadata', 'kernelspec', 'name',
   ], 'python2');
+  const cellID = notebook.get('cellOrder').first()
+  notebook = notebook.update('cellMap', (cells) => cells.setIn([cellID, 'inputHidden'], true));
```
Comment (captainsafia) [inline test/utils.js]: Can you change this so that the changes to the notebook document are made in the test as opposed to inside the utilities?

File: test/renderer/menu-spec.js [hunk 2]
```diff
@@ -178,6 +178,19 @@ describe('menu', () => {
     });
   });
 
+  describe('dispatchUnhideAll', () => {
+    it('dispatches changeInputVisibility for hidden code cells', () => {
+      const store = dummyStore();
```
Comment (captainsafia) [inline test/renderer/menu-spec.js]: As mentioned below, the store should be configured to hide one of the inputs here. You'll notice that the `dummyStore` function takes a config object. You can add a `hideAll` config option to this and use it to conditionally set the `notebook` in the `DocumentRecord`.

**Review by captainsafia — CHANGES_REQUESTED** [review]

**Comment by captainsafia** [comment]
Thanks for the PR, Adam! I posted some comments inline. Let me know if you have any questions.

File: test/renderer/menu-spec.js (hunk 2 above)
Comment (aleury) [reply test/renderer/menu-spec.js]: Ah okay. My original desire was to configure it from the test case but wasn't sure of the best approach. Thanks for the suggestion!

Comment (captainsafia) [reply test/renderer/menu-spec.js]: Yep! Your hunch was totally right.

Also, it looks like you've got to make a sacrifice to appease our linter... 😝

**Comment by aleury** [comment]
It looks like eslint doesn't like my empty `div` placeholder:

```
/home/travis/build/nteract/nteract/src/notebook/components/cell/code-cell.js
  68:20  error  Empty components are self-closing  react/self-closing-comp
```

Do you have any suggestions on how I should fix this?

**Comment by aleury** [comment]
I believe I fixed it. Didn't have my linter enabled. 😝

**Comment by captainsafia** [comment]
> Do you have any suggestions on how I should fix this?

`<div className="input-container invisible" />` oughta do it.

**Comment by aleury** [comment]
PR has been updated. Let me know if there's anything else you would like me to change.

**Comment by captainsafia** [comment]
Perfect! Thanks so much Adam! 👊🏽👏🏽

**Comment by aleury** [comment]
Thanks for your help @captainsafia! I love this project and hope to have the opportunity to contribute more in the future. 😄

**Comment by captainsafia** [comment]
Yay! Glad that you're a part of our community! Looking forward to more PRs. 🙂

**Comment by rgbkrk** [comment]
_Awesome_ welcome to the nteract party @aleury! :tada:

File: src/notebook/components/cell/code-cell.js [hunk 3]
```diff
@@ -65,7 +65,7 @@ class CodeCell extends React.Component {
               focusAbove={this.props.focusAbove}
               focusBelow={this.props.focusBelow}
             />
-          </div> : null
+          </div> : <div className="input-container invisible" />
```
Comment (rgbkrk) [inline src/notebook/components/cell/code-cell.js:68]: Love that you left this open for styling directly.

File: static/styles/main.css [hunk 4]
```diff
@@ -245,6 +245,10 @@ blockquote p {
     flex-direction: row;
 }
 
+.cell .input-container.invisible {
+    height: 34px;
+}
```
Comment (rgbkrk) [inline static/styles/main.css:250]: 👍

File: test/renderer/menu-spec.js [hunk 5]
```diff
@@ -290,6 +303,7 @@ describe('menu', () => {
         'menu:new-kernel',
         'menu:run-all',
         'menu:clear-all',
+        'menu:unhide-all',
```
Comment (rgbkrk) [inline test/renderer/menu-spec.js:306]: With tests too, next level! Thank you.
