### PR TITLE
Fixed toggling output exanded

### LINKED ISSUE #4971: "Toggle Output Expanded" does not do anything
**Application or Package Used**
stateful-components
nteract Desktop

**Describe the bug**
"Toggle Output Expanded" does not do anything

**To Reproduce**

1. Run cell with following code
```
for i in range(0,50):
  print(i);
```
2. Observe in inspector (output has "expanded" class)
3. Toggle Output Expanded
4. Observe in inspector. Notice "expanded" class is still there. No change.

### PR DESCRIPTION
**Pull request by miduncan**
Closes #4971

### CODE REVIEW

**Comment by miduncan** [comment]
Any ideas on how to get the code coverage bot to run again? It seems to have not updated.

**Comment by captainsafia** [comment]
> Any ideas on how to get the code coverage bot to run again? It seems to have not updated.

Hmmmm...something must've gotten stuck in the part of our build configuration that passes coverage stats generated in the CircleCI test step to the Codecov system. I will see if re-running the build for this PR will resolve this issue.

File: packages/reducers/src/core/entities/contents/notebook.ts [hunk 1]
```diff
@@ -477,7 +477,7 @@ function unmarkCellAsDeleting(
 
 function deleteCellFromState(
   state: NotebookModel,
-  action: actionTypes.DeleteCell,
+  action: actionTypes.DeleteCell
```
Comment (captainsafia) [inline packages/reducers/src/core/entities/contents/notebook.ts:480]: Let's add a test for these reducer changes as well.

File: packages/stateful-components/src/outputs/index.tsx [hunk 2]
```diff
@@ -58,7 +58,7 @@ export const makeMapStateToProps = (
         expanded =
           cell.cell_type === "code" &&
           (cell.getIn(["metadata", "outputExpanded"]) ||
-            !cell.getIn(["metadata", "collapsed"]));
+            cell.getIn(["metadata", "collapsed"]) === false);
```
Comment (captainsafia) [inline packages/stateful-components/src/outputs/index.tsx]: Nit: Since the `metadata.collapsed` property is now supported in the notebook format, let's move that one first.

File: packages/commutable/src/cells.ts [hunk 3]
```diff
@@ -25,6 +25,7 @@ export const makeCodeCell = Record<CodeCellParams>({
   execution_count: null,
   metadata: ImmutableMap({
     collapsed: false,
+    outputExpanded: true,
```
Comment (captainsafia) [inline packages/commutable/src/cells.ts:28]: Since `metadata.collapsed` is the officially supported attribute for toggling expansion for the notebook format, let's set that in commutable instead of the `outputExpanded` property.

This will set us up to remove support for the `outputExpanded` property and instead rely on the `metadata.collapsed` property.

We went through a similar transition for the `jupyter.source_hidden` and `jupyter.outputs_hidden` metadata properties listed below.

**Review by captainsafia — APPROVED** [review]
No glaring issues worthy of a block.

I left some comments about adding more tests and setting us up to deprecate `outputExpanded` in favor of the official `metadata.collapsed` property.

Thanks for submitting this change.

File: packages/commutable/src/cells.ts (hunk 3 above)
Comment (miduncan) [reply packages/commutable/src/cells.ts:28]: If we are going to look at both fields (I assume for compatibility), I think we really should be setting both fields. Otherwise we set ourselves up for bugs where `outputExpanded` is true but our button just toggles `collapsed`, in which case the cell will always be expanded because it looks at both.

I think the best move eventually is to read the both values, but if it is `outputExpanded` to delete that field and replace it with `expanded`. I think that work should come when we want to deprecate, though, not this.

File: packages/reducers/src/core/entities/contents/notebook.ts (hunk 1 above)
Comment (miduncan) [reply packages/reducers/src/core/entities/contents/notebook.ts:480]: I'll update the existing one. Since it doesn't add any new logic or code paths, though, I don't think a new test would increase any coverage here or provide any new information.

**Comment by willingc** [comment]
Ping @captainsafia. I tried to merge this and reran the tests but the PR will not let me override and merge.

**Review by willingc — APPROVED** [review]
