### PR TITLE
Find kernelspecs using Jupyter CLI instead of scanning paths

### LINKED ISSUE #4187: Kernel relay raises error if non-directory is found in a kernels directory
right now if you try to list all kernelspecs you get an error if there is a non-directory in the kernels directory.

Query:
```
query GetKernels {
  listKernelSpecs {
    name
  }
}
```

```
{
  "errors": [
    {
      "message": "ENOTDIR: not a directory, scandir '~/Library/Jupyter/kernels/.DS_Store'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "listKernelSpecs"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "errno": -20,
          "code": "ENOTDIR",
          "syscall": "scandir",
          "path": "~/Library/Jupyter/kernels/.DS_Store",
          "stacktrace": [
            "Error: ENOTDIR: not a directory, scandir '~/Library/Jupyter/kernels/.DS_Store'"
          ]
        }
      }
    }
  ],
  "data": null
}
```

### PR DESCRIPTION
**Pull request by emzeq**
- [X] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)

Closes #4187

### CODE REVIEW

**Comment by willingc** [comment]
Thanks for the PR. I've requested reviews from a few people.

File: packages/fs-kernels/src/kernelspecs.ts [hunk 1]
```diff
@@ -21,72 +21,23 @@ export interface KernelSpec {
...
-    if (!mustExist && error.code === "ENOENT") {
-      return [];
-    }
-    throw error;
-  }
+function augmentKernelResources(resources: KernelResourceByName): void {
+  Object.keys(resources).forEach(async name => {
+    const resource = resources[name];
+    resource.name = name;
+    const readdir = promisify(fs.readdir);
```
Comment (rgbkrk) [inline packages/fs-kernels/src/kernelspecs.ts]: Instead of creating this here, I'd do it at the top of the module.

File: .circleci/config.yml [hunk 2]
```diff
@@ -20,6 +20,7 @@ jobs:
             # fallback to using the latest cache if no exact match is found
             - yarn-packages-
 
+      - run: echo 'export PATH=/home/circleci/.local/bin:$PATH' >> $BASH_ENV
```
Comment (captainsafia) [inline .circleci/config.yml:23]: For posterity's sake, why was this added to the config?

File: packages/fs-kernels/src/kernelspecs.ts [hunk 3]
```diff
@@ -21,72 +21,23 @@ export interface KernelSpec {
...
-      name: fileName,
-      resourceDir: path.join(directory, fileName)
-    }));
-  } catch (error) {
-    if (!mustExist && error.code === "ENOENT") {
-      return [];
-    }
-    throw error;
-  }
+function augmentKernelResources(resources: KernelResourceByName): void {
```
Comment (captainsafia) [inline packages/fs-kernels/src/kernelspecs.ts]: I think it would make more sense for this function to create a new `resources` object instead of modifying the one that is passed to it.

**Review by captainsafia — COMMENTED** [review]
Looks good overall! Left a question and some feedback inline.

File: .circleci/config.yml (hunk 2 above)
Comment (emzeq) [reply .circleci/config.yml:23]: The tests on https://github.com/nteract/nteract/blob/862f6ac70efa7a78387e12d8988d689aeb33ecee/.circleci/config.yml#L37 now require the path be configured. I added it here instead of duplicating what was on https://github.com/nteract/nteract/blob/9a0ad1cc6be69e5ceef380644bfb55f0c81729b3/.circleci/config.yml#L54

File: packages/fs-kernels/src/kernelspecs.ts (hunk 3 above)
Comment (emzeq) [reply packages/fs-kernels/src/kernelspecs.ts]: Great point. Fixed.

File: packages/fs-kernels/src/kernelspecs.ts (hunk 1 above)
Comment (emzeq) [reply packages/fs-kernels/src/kernelspecs.ts]: Whoops! Fixed.

**Review by captainsafia — APPROVED** [review]
Thanks for taking the time to create and update this PR, @emzeq! I'll merge this now.

**Comment by willingc** [comment]
Thanks for the contribution @emzeq 🎉
