### PR TITLE
Display error catch

### LINKED ISSUE #2026: Use componentDidCatch within transforms
Especially those that execute code or create react elements directly. If `transform-vdom` creates React code that can cause React to crash, it brings down the whole app. Implement [`componentDidCatch`](https://reactjs.org/docs/react-component.html#componentdidcatch) for the transforms, especially `transform-vdom`.

* [ ] `@nteract/transform-vdom`
* [ ] `@nteract/transforms`
* [ ] `@nteract/display-area`

### PR DESCRIPTION
**Pull request by mpacer**
OK…

So this should take care of everything I was trying to do in #2030 #2029 and then close #2026.

Happy to work on the formatting for the error, but this seems much more of an idiomatic approach than either #2030 or #2029.

### CODE REVIEW

**Comment by mpacer** [comment]
I'm really confused, when I run this locally returning the childrens' props… 

any thoughts would be appreciated.

**Comment by rgbkrk** [comment]
This is looking good, I’ll take it for a spin locally later today. Thanks for finding the cleanest way to go about this.

**Comment by rgbkrk** [comment]
Looking good.

screen shot 2017-10-31 at 10 29 39 am

I'll get the tests updated and put some formatting in for the message.

**Comment by rgbkrk** [comment]
screen shot 2017-10-31 at 11 00 26 am

**Comment by rgbkrk** [comment]
Expanded:

screen shot 2017-10-31 at 11 02 08 am

File: packages/display-area/src/richest-mime.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 // @flow
-import * as React from "react";
+import React from "react";
```
Comment (rgbkrk) [inline packages/display-area/src/richest-mime.js]: Running through why I made some changes...

The default export on React should be preferred here.

File: packages/display-area/src/richest-mime.js [hunk 2]
```diff
@@ -14,37 +14,62 @@ type Props = {
 };
 
 type ErrorProps = {
-  children?: React.Node
+  children?: any
```
Comment (rgbkrk) [inline packages/display-area/src/richest-mime.js]: Actually maybe I shouldn't have changed this one...

File: packages/display-area/src/richest-mime.js [hunk 3]
```diff
@@ -14,37 +14,62 @@ type Props = {
...
+};
+
+type ErrorInfo = {
+  componentStack: string
```
Comment (rgbkrk) [inline packages/display-area/src/richest-mime.js]: I wanted to have a consistent type here, I imagine we'll move these into a package we use across the overall app.

I wonder if we could/should use these types directly: https://github.com/facebook/react/blob/2b3592331efd4b41f19de521528f664b870393e5/packages/react-reconciler/src/ReactFiberScheduler.js#L70

File: packages/display-area/src/richest-mime.js [hunk 4]
```diff
@@ -13,6 +13,69 @@ type Props = {
...
+  error: ?Error,
+  info: ?ErrorInfo
+};
+
+type FallbackProps = {
+  componentStack: string,
+  error: Error
+};
+
+const Fallback = ({ componentStack, error }: FallbackProps) => (
```
Comment (mpacer) [inline packages/display-area/src/richest-mime.js:30]: Great idea to make this a standalone component. This is making me think the ErrorBoundary should exist as a separate module so anywhere in the codebase can access it.

**Review by mpacer — COMMENTED** [review]
I think this should be in its own module what should I read to figure out how to manage that infrastructure change?

File: packages/display-area/src/richest-mime.js (hunk 4 above)
Comment (rgbkrk) [reply packages/display-area/src/richest-mime.js:30]: Amusingly my next commit completely counters that by making `RichestMime` be an error boundary itself.

Motivation:

* Simplified testing around the one component
* Semantically, we care about a single output that doesn't render properly in that we can take other actions based on this (scrubbing it from the notebook, reporting errors specific to this, etc.)

Comment (mpacer) [reply packages/display-area/src/richest-mime.js:30]: Yep I was thinking errorBoundary should be a module that takes a renderprop and as we need it we can customise the rendering (in this case using the Fallback Component).

Comment (mpacer) [reply packages/display-area/src/richest-mime.js:30]: To clarify, I think semantically it makes more sense to have an ErrorBoundary wherever we discover the need for  it, customizing the formatting to be specific to that case.

And with that consideration… I would normally hesitate from making code architecture decisions on the sole basis of it being a test more akin to what was already present. 

Basically I think we'll eventually want error handling elsewhere and we should deal with these problems (incl. the testing issue) in a way that makes it easy for people in the future to add error handling without needing to work through these issues again.

Comment (rgbkrk) [reply packages/display-area/src/richest-mime.js:30]: Since React 16 is pretty new, I think they wrote out `ErrorBoundary` as a concept when really there's only one new lifecycle method -- `componentDidCatch`. The way I'd probably shape this after is to list the offending mimetype, data, etc. since we can give more context right here.

**Comment by rgbkrk** [comment]
Thanks for tackling this @mpacer, glad we have it in!
