### PR TITLE
Use 'scrolled' instead of 'collapsed' metadata property for output scrolling

### LINKED ISSUE #5527: Non-standard use of "collapsed" metadata property
**Application or Package Used**
nteract web

**Describe the bug**
in #4972, nteract started to use the "collapsed" metadata property to indicate whether an output is shown in a scrolled div or otherwise shown in its entirety. However, the standard field for that is not "collapsed", but rather "scrolled" (see official ipynb schema [here](https://github.com/jupyter/nbformat/blob/373d926154d47fa09c453958720786f8ee8aa737/nbformat/v4/nbformat.v4.schema.json#L252))

In Jupyter Classic, this is what an output with `"scrolled": true` looks like (which is what we want):
image

Whereas this is an output with `"collapsed": true`
image

Note that in a collapsed output there's a clickable rectangle that shows up and that allows expanding the output:
image

### PR DESCRIPTION
**Pull request by jruales**
Using "scrolled" instead of "collapsed" for representing outputs with a scrolled div, to better align with [official ipynb format](https://github.com/jupyter/nbformat/blob/master/nbformat/v4/nbformat.v4.schema.json).

- [X] I have read the [Contributor Guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md)
- [X] I have updated the changelogs/current_changelog.md file with some information about the change that I am making the appropriate file.
- [X] I have validated or unit-tested the changes that I have made.
- [x] I have run through the TEST_PLAN.md to ensure that my change does not break anything else.

### CODE REVIEW

File: packages/commutable/src/v3.ts [hunk 1]
```diff
@@ -86,8 +86,6 @@ export interface HeadingCell {
 
 export interface CodeCell {
   cell_type: "code";
-  language: string;
```
Comment (miduncan) [inline packages/commutable/src/v3.ts]: Why are we touching the language field?

**Review by miduncan — COMMENTED** [review]
For existing notebooks with the collapsed field, how are we handling that? Are we just not doing anything with them?

File: packages/commutable/src/v3.ts (hunk 1 above)
Comment (jruales) [reply packages/commutable/src/v3.ts]: The `language` and `collapsed` fields are not being used here, so I removed them as cleanup

**Comment by jruales** [comment]
> For existing notebooks with the collapsed field, how are we handling that? Are we just not doing anything with them?

@miduncan At the moment, we're not doing anything about those fields. Do you think that we should wipe that field from any notebook we open? Note that the collapsed field indicates in Jupyter classic that an output is collapsed like this:
image

File: packages/commutable/src/cells.ts [hunk 2]
```diff
@@ -25,7 +25,6 @@ export const makeCodeCell = Record<CodeCellParams>({
   cell_type: "code",
   execution_count: null,
   metadata: ImmutableMap({
-    collapsed: true,
```
Comment (captainsafia) [inline packages/commutable/src/cells.ts:28]: Why not default to `scrolled=true` here?

Comment (jruales) [reply packages/commutable/src/cells.ts:28]: - Jupyter Notebook by default doesn't define it
- The actual default value we would want is `"auto"`, but I haven't implemented `"auto"` scrolling yet. ("scrolled" can be true, false, or "auto", and it's an optional property)
- If the `collapsed` property is set to `true`, then it would not be able to go back to `"auto"` by toggling. At least in Jupyter Notebook, the value only acts as "auto" as default, and then when you toggle it, it just goes to true or false and never back to "auto". So I wouldn't want notebooks out there to all have "scrolled":"true" since otherwise the auto scrolling would not apply to those existing notebooks

File: packages/commutable/src/v3.ts (hunk 1 above)
Comment (jruales) [reply packages/commutable/src/v3.ts]: I've reverted the changes to v3.ts since they seem to be for an older version of commutable and I don't want to touch that

**Comment by jruales** [comment]
@miduncan @captainsafia any other comments?

**Review by captainsafia — APPROVED** [review]
This LGTM. I suspect the implementation of `auto` support will shift things quite a bit.

**Review by miduncan — APPROVED** [review]

**Comment by MSeal** [comment]
Thanks @jruales !
