### PR TITLE
Fix appendOutput reducer not updating previous cells with the same display id

### LINKED ISSUE #4514: The `display-update` Example notebook is not working as described - display() without update=True does not update previous display outputs
**Application or Package Used**
I have reproduced this on:
- nteract desktop
- nteract on jupyter

**Describe the bug**
The `display-update` Example notebook is not working as described - display() without update=True does not update previous display outputs

**To Reproduce**

1. Open the `display-update` Example notebook
2. Run all commands up until and including `h2 = display('spoiler alert: output updated in both', display_id='some_destination')`

**Expected behavior**
The output should be updated in both destinations.

**Actual behavior**
The output is only updated in the cell directly below the command.

**Desktop:**
- OS: macOS 10.14.6
- Browser: nteract 0.14.5
- Version 0.14.5

**Additional context**
The subsequent command that uses display() with update=True works as intended.

The notebook in its entirety works as intended in the jupyter notebook environment using the same kernel.

### PR DESCRIPTION
**Pull request by CrystallineCat**
Fixes #4514.

### CODE REVIEW

**Comment by CrystallineCat** [comment]
Unsure what causes the compiler to fail on CircleCI.

File: packages/reducers/src/core/entities/contents/notebook.ts [hunk 1]
```diff
@@ -17,10 +17,11 @@ import {
   insertCellAt,
   makeCodeCell,
   makeMarkdownCell,
-  makeRawCell,
+  makeRawCell, OnDiskDisplayData, OnDiskExecuteResult, OnDiskMediaBundle,
   OnDiskOutput,
   OnDiskStreamOutput
 } from "@nteract/commutable";
+import { JSONObject } from "@nteract/data-explorer/lib/types";
```
Comment (captainsafia) [inline packages/reducers/src/core/entities/contents/notebook.ts]: This is causing the build to fail. Try importing `JSONObject` from `@nteract/commutable` instead.

File: packages/reducers/src/core/entities/contents/notebook.ts [hunk 2]
```diff
@@ -204,6 +205,53 @@ function clearAllOutputs(
     .set("transient", transient);
 }
 
+// Utility function used in two reducers below
+function updateAllDisplaysWithID(
+  state: NotebookModel,
+  content: OnDiskExecuteResult | OnDiskDisplayData | {
```
Comment (captainsafia) [inline packages/reducers/src/core/entities/contents/notebook.ts]: Can we move the last type to a named interface?

**Review by captainsafia — COMMENTED** [review]
Left some feedback and a note inline about why the build is failing. Thanks for submitting this PR!

File: packages/reducers/src/core/entities/contents/notebook.ts (hunk 2 above)
Comment (rgbkrk) [reply packages/reducers/src/core/entities/contents/notebook.ts]: Guess the name could be `OnDiskOutput` or something?

Comment (rgbkrk) [reply packages/reducers/src/core/entities/contents/notebook.ts]: Though I guess there are only these three and they maybe only matter as types here.

`UpdatableOutputContent` as a name?

File: packages/reducers/src/core/entities/contents/notebook.ts (hunk 1 above)
Comment (CrystallineCat) [reply packages/reducers/src/core/entities/contents/notebook.ts]: Thank you, that fixed it!

File: packages/reducers/src/core/entities/contents/notebook.ts (hunk 2 above)
Comment (CrystallineCat) [reply packages/reducers/src/core/entities/contents/notebook.ts]: I moved the type to an interface, and added an alias for the three types. I moved the interface to @nteract/messaging, since that seems to be where the data originated from.

**Review by rgbkrk — APPROVED** [review]
Love it!

File: packages/reducers/__tests__/document.spec.ts [hunk 3]
```diff
@@ -875,6 +875,29 @@ describe("updateDisplay", () => {
...
+          data: { "text/plain": "shennagins afoot" },
+          metadata: Immutable.Map({})
+        }),
+        makeExecuteResult({
+          output_type: "execute_result",
+          data: { "text/plain": "shennagins afoot" },
+          metadata: Immutable.Map({})
+        })
+      ])
+    );
```
Comment (rgbkrk) [inline packages/reducers/__tests__/document.spec.ts:898]: Especially happy about extra tests. 😄

**Review by rgbkrk — APPROVED** [review]
