### PR TITLE
bug(saveAs): Use remote.app to query app

### LINKED ISSUE #783: `save` deferral to `saveAs` not working
This seems to be an issue with the new launch filename mechanics:

screen shot 2016-09-17 at 11 53 25 am

Reproduction steps:
- Open a new notebook (npm run start in dev for example)
  command-s (to save)
- Error notification pops up

### PR DESCRIPTION
**Pull request by captainsafia**
Closes #783.

### CODE REVIEW

File: src/notebook/menu.js [hunk 1]
```diff
@@ -78,7 +77,7 @@ export function triggerWindowRefresh(store, filename) {
 }
 
 export function triggerSaveAs(store) {
-  showSaveAsDialog(app.getPath('home'))
+  showSaveAsDialog(remote.app.getPath('home'))
```
Comment (rgbkrk) [inline src/notebook/menu.js:80]: Ah, great!

**Review by rgbkrk — APPROVED** [review]
