### PR TITLE
fix(geo): detect and fallback to tile themes

### LINKED ISSUE #1093: determine a strategy for picking tiles
in `componentDidMount` function within `src/notebook/components/transforms/geojson.js`

### PR DESCRIPTION
**Pull request by rgbkrk**
Fixes #1093.

/cc @gnestor

### CODE REVIEW

File: src/notebook/components/transforms/geojson.js [hunk 1]
```diff
@@ -13,6 +13,18 @@ L.Icon.Default.imagePath = '../node_modules/leaflet/dist/images/';
...
 
+type TileTheme = 'dark' | 'light';
+
+function getTheme(theme : string = 'light'): TileTheme {
+  switch (theme) {
+    case 'light':
+    case 'dark':
+      return theme;
+    default:
+      return 'light';
```
Comment (rgbkrk) [inline src/notebook/components/transforms/geojson.js]: The one uncovered line decreasing coverage here is funny.

**Review by lgeiger — APPROVED** [review]
Nice 🎉
