### PR TITLE
fix: handle surrogate pairs

### LINKED ISSUE #1706: handle surrogate pairs in character offsets
CodeMirror indices must be converted from UTF-16 units to actual character offsets:

> I think it makes the most sense for the protocol spec to be 'characters', so if CodeMirror indices are returning UTF-16 units, it ought to be the responsibility of the Jupyter javascript to deal with surrogate pairs and turn that into actual character offsets. - @minrk

See:

* https://github.com/jupyter/notebook/pull/2509
* https://github.com/jupyter/jupyter_client/issues/259

### PR DESCRIPTION
**Pull request by rgbkrk**
Fixes #1706

* [x] completion
* [x] introspection

/cc @minrk @Carreau how's this look for a start?

Finally got to this @stevengj, hoping to get it done to make a release in the next few days.

### CODE REVIEW

File: packages/editor/src/complete.js [hunk 1]
```diff
@@ -63,14 +65,37 @@ export const expand_completions = editor => results => {
...
+    // and negative start relative to that
+    end = editor.indexFromPos(editor.getCursor());
+    if (start === null) {
+      start = end;
+    } else if (start < 0) {
+      start = end + start;
+    }
+  } else {
+    // handle surrogate pairs
+    // HACK: This seems susceptible to timing issues, we could verify changes in
```
Comment (minrk) [inline packages/editor/src/complete.js:84]: Re: timing issue, you could cache the value keyed by the request msg_id and use that for transforming the value back. It might also be worthwhile to just dismiss completions if input changed since completion was requested, even excluding the potential (unlikely) surrogate measurement issue.

I'm not sure how often `import m<tab>atpl<completion arrives with matplotlib>` happens or how well you handle it.

**Review by minrk — APPROVED** [review]

File: packages/editor/src/complete.js (hunk 1 above)
Comment (rgbkrk) [reply packages/editor/src/complete.js:84]: Typically with network latency (remote deployments, crappy wifi) and with slow kernels (Toree, other JVM based kernels) this comes up. What makes matters a little bit worse with nteract is that we do typeahead instead of tab complete. CodeMirror seems smart enough to ignore it if the cursor is not where the suggestion is though, with my limited testing.

**Comment by rgbkrk** [comment]
I recommitted as you by the way @minrk, since I yoinked this code out of jupyter/notebook while I was offline.

**Review by Carreau — APPROVED** [review]
The potential timing issue also exist in classic notebook.

**Comment by rgbkrk** [comment]
Thank you both!
