### PR TITLE
Auto-adds http prefix to www. links and doesn't hyperlink partial link matches

### LINKED ISSUE #4964: Links starting with "www" or surrounded in quotes are treated as relative links
**Application or Package Used**
ansi-to-react

**Describe the bug**
Links starting with "www" or surrounded in quotes are treated as relative links

**To Reproduce**

1. In code cell, type `print('www.google.com')`
2. Run cell
3. Click link
4. Observe URL is now http://example.com/www.google.com

1. In code cell, type 
```
c = 'http://www.google.com'
c
```
2. Run cell
3. Click link
4. Observe URL is http://example.com/'http://www.google.com'

### PR DESCRIPTION
**Pull request by miduncan**
Closes #4964

### CODE REVIEW

File: packages/ansi-to-react/src/index.ts [hunk 1]
```diff
@@ -116,21 +117,20 @@ function convertBundleIntoReact(
         return words;
       }
 
+      const href = word.startsWith("www.") ? `http://${word}` : word;
```
Comment (captainsafia) [inline packages/ansi-to-react/src/index.ts:122]: This won't capture links like `google.com`. Can we invert the way this works and instead have  it check to see if `http://` is a substring of the word and add it to the beginning if not?

Also nit: Let's use `http://` instead of `https://`.

EDIT: The above should be be Let's use **`https://`** instead of **`http://`**.

Comment (captainsafia) [reply packages/ansi-to-react/src/index.ts:122]: Also, let's add a comment to explain why we are doing this,

File: packages/ansi-to-react/src/index.ts [hunk 2]
```diff
@@ -116,21 +117,20 @@ function convertBundleIntoReact(
...
       words.push(
         React.createElement(
           "a",
           {
             key: index,
-            href: word,
+            href: href,
```
Comment (captainsafia) [inline packages/ansi-to-react/src/index.ts]: Nit: this can just be `href: href` instead of `href`.

**Review by captainsafia — COMMENTED** [review]
Welp! My review of this was stuck in the draft.

I left some comments inline.

File: packages/ansi-to-react/src/index.ts (hunk 1 above)
Comment (miduncan) [reply packages/ansi-to-react/src/index.ts:122]: I think that is out of scope of this PR, as we need a broader discussion of if those types of links (like `google.com`) should be supported. Currently they are not, the regular expression expects a `http` or `www` to start. Personally I think we shouldn't-- most things that try to help you out with linking don't support them, plus then we have to keep up with all of the domain endings and not false positive on things like "ASP.NET"

I'm assuming you meant use `https` since it already uses `http` right now. The problem is that we can't assume a website supports https, many don't.

I can definitely add a comment, though.

Comment (captainsafia) [reply packages/ansi-to-react/src/index.ts:122]: > I think that is out of scope of this PR, as we need a broader discussion of if those types of links (like google.com) should be supported. Currently they are not, the regular expression expects a http or www to start. Personally I think we shouldn't-- most things that try to help you out with linking don't support them, plus then we have to keep up with all of the domain endings and not false positive on things like "ASP.NET"

Seems reasonable.

> I'm assuming you meant use https since it already uses http right now. The problem is that we can't assume a website supports https, many don't.

I think the opposite is true. Considering most browsers will through a warning if a user tries to navigate to an unsecured domain, we should be prudent and redirect to HTTPS when possible.

Comment (miduncan) [reply packages/ansi-to-react/src/index.ts:122]: It will show an icon that it isn't secure, but the warning page is for when you go to an https link that doesn't have a trusted certificate so it needs to fall back to http.

For comparison, Microsoft Word and Outlook also only add http
image

Usually if the website requires https, the http link will redirect to https.

**Review by captainsafia — APPROVED** [review]
