### PR TITLE
Show warning message if no kernels

### LINKED ISSUE #490: Provide error messages when no kernelspecs detected
When I run `npm run start` the app get's stuck on the "Loading..." screen below. Also, under the `File > New` menu, I only see `Bash` as an option and no `Python`. 

I don't see any error message in the terminal window. Any ideas on what I am doing wrong?

image

### PR DESCRIPTION
**Pull request by captainsafia**
Closes #490.

Shows a warning when no kernels are installed.

screen shot 2016-09-14 at 12 04 19 pm

### CODE REVIEW

File: src/main/menu.js [hunk 1]
```diff
@@ -357,40 +357,55 @@ export function loadFullMenu() {
...
+        ],
+      };
+    } else {
+      dialog.showMessageBox({
+        type: 'warning',
+        title: 'No Kernels Installed',
+        buttons: [],
+        message: 'No kernels are installed on your system.',
+        detail: 'No kernels are installed on your system so you will not be' +
+                'able to execute code cells in any language.',
```
Comment (jdetle) [inline src/main/menu.js]: should be a space  after be?

Comment (captainsafia) [reply src/main/menu.js]: Good catch!

File: src/main/menu.js [hunk 2]
```diff
@@ -357,40 +357,55 @@ export function loadFullMenu() {
...
+      }, (index) => {
+        const languageMenu = {
+          label: '&Language',
+        };
+      });
```
Comment (rgbkrk) [inline src/main/menu.js:414]: Excellent!

We should probably link to a help page for this too. They need a next step so we don't leave them lost.

**Review by rgbkrk — APPROVED** [review]
