### PR TITLE
Fix for Box based widgets

### LINKED ISSUE #4640: Box-based ipywidgets do not render
**Application or Package Used**
@nteract/jupyter-widgets

**Describe the bug**
The current implementation of the jupyter-widgets package does not render Box-based widgets like Box, VBox, and HBox.

**To Reproduce**

1. Create a new notebook.
2. Attempt to create a box widget. Note that no widget is not rendered.

```
import ipywidgets
items = [ipywidgets.Label(str(i)) for i in range(4)]
ipywidgets.Box(items)
```

**Expected behavior**
Layout-based widgets should render.

**Desktop (please complete the following information):**
master

### PR DESCRIPTION
**Pull request by miduncan**
Fixes #4640 
```
import ipywidgets as widgets
items = [widgets.IntSlider() for i in range(4)]
widgets.Box(items)
```
now outputs
image

### CODE REVIEW

File: packages/jupyter-widgets/src/manager/widget-manager.ts [hunk 1]
```diff
@@ -124,18 +125,30 @@ export class WidgetManager extends base.ManagerBase<DOMWidgetView> {
...
-  render_view(view: base.DOMWidgetView): void {
-    view.render();
-    view.trigger("displayed");
+  /**
+   * Render the given view to a target element
+   * @param view View to be rendered
+   * @param el Target element that the view will be rendered within
+   */
+  render_view(view: base.DOMWidgetView, el: HTMLElement): void {
+    pWidget.Widget.attach(view.pWidget, el);
```
Comment (captainsafia) [inline packages/jupyter-widgets/src/manager/widget-manager.ts:151]: Do we have to transfer all rendering control to Phosphor? I'd prefer if we kept as much of it in React as possible.

It looks like @williamstein started working on creating [a set of React controls](https://github.com/sagemathinc/cocalc/blob/master/src/smc-webapp/jupyter/widgets/controls.ts) that are [used](https://github.com/sagemathinc/cocalc/blob/master/src/smc-webapp/jupyter/widgets/manager.ts#L396) to render the Box-based views. Can we take a similar approach?

Comment (miduncan) [reply packages/jupyter-widgets/src/manager/widget-manager.ts:151]: Unfortunately, the Box widget seems to be intentionally designed to not work any other way. It creates its own Phosphor element on initialization and has an explicit check in its `setElement` function that the element is not changed to anything else. Even if you pass the element in the constructor, it will still reach this check and throw an error.

We could look at designing our own Box based views (we would actually need to replace a bit more than that to completely get rid of the dependency), but I'm not sure it's a good investment of our time this sprint.

Comment (miduncan) [reply packages/jupyter-widgets/src/manager/widget-manager.ts]: I take that back-- I don't really know the whole picture. What negatives does the existing Phosphor dependency bring with it?

**Review by captainsafia — APPROVED** [review]
Let's settle for this then replace the Box-based layouts with React controls in a follow-up.
