### PR TITLE
move records into core

### LINKED ISSUE #2408: Notebook types are wrong in @nteract/types/core/records
I just noticed that flow wasn't actually resolving the types for the records because of two things:

* `@nteract/types/core/records` resolves to the lib version
* The flow definitions are not copied for the records

It's not a simple switch though -- as soon as I "fixed" that, I found an overwhelming amount of flow errors to get through. Most of the issue is that `Immutable.Map`s are not used for the notebook when they should be (up until we switch to `Immutable.Record` in `commutable`. Honestly though, the records should be relying on commutable's types if at all possible.

### PR DESCRIPTION
**Pull request by rgbkrk**
Closes #2408, moving core records into `@nteract/core` and out of `@nteract/types`.

Necessary follow up PRs:

* Correct type inside of `selectors`.
* Address the keypath `$FlowFixMe`s

There will be some duplication in the middle of this, followed by a magical rebase that makes it look like I did it all in one ✨

### CODE REVIEW

**Comment by rgbkrk** [comment]
Rebased this against master, still more to go.

**Comment by rgbkrk** [comment]
This will definitely be rebased...

**Comment by rgbkrk** [comment]
Stopping this one without doing selectors. I'll do a separate PR for that ball of wax.

File: applications/desktop/__tests__/renderer/native-window-spec.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ import { remote } from "electron";
 import { from } from "rxjs/observable/from";
 
 import * as nativeWindow from "../../src/notebook/native-window";
-import { makeAppRecord, makeDocumentRecord } from "@nteract/types/core/records";
+import { makeAppRecord, makeDocumentRecord } from "@nteract/core/records";
```
Comment (rgbkrk) [inline applications/desktop/__tests__/renderer/native-window-spec.js:7]: As you'll see in most of this PR, it was a lot of turning `@nteract/types/core/records` into `@nteract/core/records`

File: applications/desktop/src/notebook/epics/zeromq-kernels.js [hunk 2]
```diff
@@ -39,7 +39,9 @@ import * as jmp from "jmp";
 
 import type { NewKernelAction } from "@nteract/core/actionTypes";
 
-import type { KernelInfo, LocalKernelProps } from "@nteract/types/core/records";
+import type { KernelInfo, LocalKernelProps } from "@nteract/core/src/records";
```
Comment (rgbkrk) [inline applications/desktop/src/notebook/epics/zeromq-kernels.js:42]: Since the top level `packages/core/records` doesn't re-export the types, we pull these out of `src`.

File: applications/desktop/src/notebook/index.js [hunk 3]
```diff
@@ -26,8 +26,8 @@ import {
   makeAppRecord,
   makeDesktopHostRecord,
   makeDocumentRecord,
-  CommsRecord
-} from "@nteract/types/core/records";
+  makeCommsRecord
```
Comment (rgbkrk) [inline applications/desktop/src/notebook/index.js:29]: Wise change I probably could have done in another PR. It was confusing me as to if this was a type or something else, when it was another record creator.

File: applications/desktop/src/notebook/menu.js [hunk 4]
```diff
@@ -269,6 +269,7 @@ export function exportPDF(
   notificationSystem: *
 ): void {
   const state = store.getState();
+  // $FlowFixMe: This should be using a selector first and foremost
```
Comment (rgbkrk) [inline applications/desktop/src/notebook/menu.js:272]: I'll fix this in a follow up PR when I do the selector bits.

File: packages/core/src/actionTypes.js [hunk 5]
```diff
@@ -1,9 +1,7 @@
 /* @flow */
 
-import type {
-  KernelspecsRef,
-  KernelspecProps
-} from "@nteract/types/core/records";
+import type { KernelspecsRef, KernelspecProps } from "./records";
```
Comment (rgbkrk) [inline packages/core/src/actionTypes.js]: I'll merge this into a later import in this file.

File: packages/core/src/records/index.js [hunk 6]
```diff
@@ -142,7 +150,7 @@ export type NotebookMetadata = {
   // orig_nbformat?: number,
 };
 
-export type Notebook = {
+export type NotebookRecordProps = {
```
Comment (rgbkrk) [inline packages/core/src/records/index.js:153]: Note: This type isn't used at all here.

File: packages/core/src/records/index.js [hunk 7]
```diff
@@ -168,7 +176,7 @@ export const makeAppRecord: RecordFactory<AppRecordProps> = Record({
   host: null,
   githubToken: null,
   notificationSystem: {
-    addNotification: msg => {
+    addNotification: (msg: { level?: "error" | "warning" }) => {
```
Comment (rgbkrk) [inline packages/core/src/records/index.js:179]: Did this just to increase coverage.

File: packages/core/src/records/index.js [hunk 8]
```diff
@@ -192,7 +200,10 @@ export const makeAppRecord: RecordFactory<AppRecordProps> = Record({
 export type AppRecord = RecordOf<AppRecordProps>;
 
 type DocumentRecordProps = {
-  notebook: ?Notebook,
+  // TODO: This _needs_ to become a Record
+  notebook: ?Map<string, any>,
+  savedNotebook: ?Map<string, any>,
```
Comment (rgbkrk) [inline packages/core/src/records/index.js:205]: We were missing this property on the document record.

File: applications/desktop/__tests__/renderer/native-window-spec.js (hunk 1 above)
Comment (theengineear) [reply applications/desktop/__tests__/renderer/native-window-spec.js:7]: I've added `@nteract/core/types`, do you think we should keep `/records` in that? We're starting to duplicate work as you mentioned, we should make sure we have a plan to resolve the duplication in the future. Thoughts?
