### PR TITLE
Fix classic theme

### LINKED ISSUE #1412: Fix the default theme
We've had enough changes in `main.css` that it appears have made the "classic" theme no longer match Jupyter/IPython notebook. It would be great to have it in a reasonable state again.

## Our current implementation

screen shot 2017-02-06 at 12 22 53 pm

## Jupyter notebook

screen shot 2017-02-06 at 12 24 31 pm

### PR DESCRIPTION
**Pull request by lgeiger**
Fix #1412 
bildschirmfoto 2017-02-07 um 01 03 11

### CODE REVIEW

**Comment by rgbkrk** [comment]
😂

File: src/notebook/index.js [hunk 1]
```diff
@@ -57,11 +57,11 @@ class App extends React.PureComponent {
     return (
       <Provider store={store}>
         <div>
+          <link rel="stylesheet" href="../static/styles/main.css" />
```
Comment (rgbkrk) [inline src/notebook/index.js:60]: I've been meaning to move the main.css stylesheet up for a very long time. Thanks!

**Review by rgbkrk — APPROVED** [review]
